---
title: "Publication-ready plots of multiple continuous/numeric variables/features"
description: |
  This quick tutorial will teach you how to quickly generate plots across multiple continuous variables.
author:
  - name: Jordan Gauthier 
    url: https://github.com/drjgauthier
    affiliation: Fred Hutch/University of Washington
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## Simulate longitudinal data

```{r}
df <- data.frame(matrix(nrow = 29, ncol = 40))
for (i in 1:40) {
    df[,i] <- rnorm(29,1000,250) + runif(29,0,100000)
}
df <- cbind(c(0:28),df)
colnames(df) <- c("timepoint",paste0(rep("var_",40),c(1:40)))
```

## Wrangle and graph all variables in one plot

```{r, layout="l-body-outset",fig.width=10, fig.height=8}
var_names <- dput(names(df[,-1])) # Build vector with levels in order
df %>%
  pivot_longer(cols = "var_1":"var_40",
               names_to = "variable",
               values_to = "value") %>%
  mutate(variable=fct_relevel(variable,var_names)) %>% #Reorder variables
  ggplot(aes(x = timepoint, y = value)) +
  geom_line(aes(group=variable)) +
  facet_wrap(~ variable, ncol = 6, scales = "free_y") + #scales = "free_y" allows y axis to vary across variables
  theme_bw()
```

